:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

== 그룹 멤버
---
=== 1. 그룹 멤버에 속하는지 여부 반환
Parameters::

[cols=4*,options=header]
|===
|path variable
|설명
|path variable
|설명

|userId
|유저 인덱스
|plannerId
|플래너 인덱스
|===


Request::
```http
GET /api/v1/users/1/planners/1/group HTTP/1.1
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwiaWF0IjoxNzE2MjExNzE3LCJleHAiOjE3MTYyMTI2MTd9.WW7oSRd1h1s-qPSnOiUdlMGc6C2hrDGBANaEEOBrZBM
Host: localhost:8080
```

Response::
결과 값이 `false` 인 경우 그룹 멤버와 관련된 메뉴를 숨겨야 합니다.
```http
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

false
```

=== 2. 그룹 멤버 리스트 반환
Parameters::

[cols=4*,options=header]
|===
|path variable
|설명
|path variable
|설명

|userId
|유저 인덱스
|plannerId
|플래너 인덱스
|===

Request::
```http
GET /api/v1/users/1/planners/1/group HTTP/1.1
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwiaWF0IjoxNzE2MjExNzE3LCJleHAiOjE3MTYyMTI2MTd9.WW7oSRd1h1s-qPSnOiUdlMGc6C2hrDGBANaEEOBrZBM
Host: localhost:8080
```

Response::

```http
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

[
  {
    "groupMemberId": 3,
    "userId": 3,
    "nickname": "시은",
    "userTag": 1234,
    "profileImageUrl": "",
    "isHost": true
  },
  {
    "groupMemberId": 4,
    "userId": 4,
    "nickname": "지은",
    "userTag": 1234,
    "profileImageUrl": "",
    "isHost": false
  }
]
```

=== 3. _그룹 멤버 추가_
Parameters::

[cols=2*,options=header]
|===
|path variable
|설명

|plannerId
|플래너 인덱스
|===

PUBLISH::
```
/pub/planner/{plannerId}/members/create
```
Request Body 에 아래와 같이 넣어줍니다.
```json
{
  "userId": 4
}
```

플래너를 만든 사람(Host) 은 플래너 생성 당시에 자동으로 추가됩니다.  +
때문에 *host 나 이미 추가한 사람을 다시 추가 한다면* `INVALID_VALUE_04` 코드를 반환 합니다.

SUBSCRIBE::
```
/sub/planner/{plannerId}
```
발행 주소에 제대로 값을 보내면 구독 주소에서 그룹 멤버 리스트를 반환합니다. +
실시간으로 많은 데이터가 섞여 들어오니, `type` 을 기준으로 분류해주세요.
```json
[
  {
    "type": "add-group-member",
    "message": [
      {
        "groupMemberId": 3,
        "userId": 3,
        "nickname": "시은",
        "userTag": 1234,
        "profileImageUrl": "",
        "isHost": true
      },
      {
        "groupMemberId": 4,
        "userId": 4,
        "nickname": "지은",
        "userTag": 1234,
        "profileImageUrl": "",
        "isHost": false
      }
    ]
  }
]

```


=== 4. _그룹 멤버 삭제_
Parameters::

[cols=4*,options=header]
|===
|path variable
|설명
|path variable
|설명

|plannerId
|플래너 인덱스
|memberId
|그룹 멤버 인덱스
|===


PUBLISH::
```
/pub/planner/{plannerId}/members/{memberId}/delete
```
Request Body 에 아래와 같이 넣어줍니다.
```json
{
  "groupMemberId": 3
}
```

*플래너를 만든 사람(Host) 은* 멤버를 내보낼 수 있도록 내보내기 버튼을 생성해 주세요.  +
*멤버로 초대된 사람은* 그룹을 나갈 수 있도록 나가기 버튼을 생성해 주세요. +
둘다 요청 주소는 같습니다. 사용자의 편의성과 비즈니스 로직을 위해 분류해 주세요.

SUBSCRIBE::
```
/sub/planner/{plannerId}
```
발행 주소에 제대로 값을 보내면 구독 주소에서 그룹 멤버 리스트를 반환합니다. +
실시간으로 많은 데이터가 섞여 들어오니, `type` 을 기준으로 분류해주세요.
```json
[
  {
    "type": "delete-group-member",
    "message": [
      {
        "groupMemberId": 3,
        "userId": 3,
        "nickname": "시은",
        "userTag": 1234,
        "profileImageUrl": "",
        "isHost": true
      }
    ]
  }
]

```
