name: Build and Push Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-jar.outputs.cache-key }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Cache JAR
        id: cache-jar
        uses: actions/cache@v3
        with:
          path: |
            build/libs/*.jar
          key: ${{ runner.os }}-jar-${{ github.sha }}
        env:
          cache-name: cache-jar

      - name: Prepare cache key for next job
        run: echo "cache-key=${{ runner.os }}-jar-${{ github.sha }}" >> $GITHUB_ENV

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Restore JAR from Cache
        uses: actions/cache@v3
        with:
          path: |
            build/libs/*.jar
          key: ${{ needs.build.outputs.cache-key }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: your-username/your-repo:latest
          context: .
          build-args: |
            JAR_FILE=build/libs/travel-0.0.1-SNAPSHOT.jar
  
  
